services:
  mahjong:
    build: .
    image: mahjong:250318
    container_name: mahjong
    restart: always
    ports:
      - "24301:3000"
    environment:
      JWT_SECRET: ""
      JWT_ACCESS_TOKEN_TTL: ""
      DATABASE_URL: ""
