services:
  mahjong:
    image: backend/mahjong
    container_name: backend/mahjong
    restart: always
    ports:
      - "24301:3000"
    environment:
      JWT_SECRET: ""
      JWT_ACCESS_TOKEN_TTL: ""
      DATABASE_URL: ""
